Fixed crash when using http or https URLs
The problem was caused by an incorrect way of getting the module name from the URL protocol. The exception log was:

module.js:339
    throw err;
    ^

Error: Cannot find module 'https://'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at LineReader._initStream (./linereader.js:55:5)
    at ./linereader.js:44:10
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)